/* eslint-disable global-require */
module.exports = {
    about_page: require('./about_page.json'),
    archive_page: require('./archive_page.json'),
    artist: require('./artist.json'),
    audition_page: require('./audition_page.json'),
    blog_page: require('./blog_page.json'),
    contact_page: require('./contact_page.json'),
    footer: require('./footer.json'),
    header: require('./header.json'),
    home_page: require('./home_page.json'),
    legal_page: require('./legal_page.json'),
    post: require('./post.json'),
    privacy_page: require('./privacy_page.json'),
    season: require('./season.json'),
    show: require('./show.json'),
    site_config: require('./site_config.json'),
    support_us_page: require('./support_us_page.json'),
    terms_page: require('./terms_page.json'),
};
